### PR TITLE
Add my car please

### PR DESCRIPTION
**Pull request by jatkinson**
I think it's a good one. Actually, the one.

### CODE REVIEW

**Review by nkkl — COMMENTED** [review]
Please change the title attribute to something more generic, like "car". :)

**Comment by nkkl** [comment]
I also worry a little bit that a car is not enough of a one-size-fits-all problem for this... Compared to, like, pens and spatulas.

**Comment by jatkinson** [comment]
I contend that it is enough for the conceit of the site. :) I imagine that
people will make their own decision if they have particular personal needs
or tastes, with any of these objects.
Of course, it's your site and you're welcome to reject the request if you
think it detracts from the purpose.

**Comment by nkkl** [comment]
I worry about the scope a little. Because presumably next year the right car will be different, whereas the right pen and right spatula change more on a 5+ year cadence.

**Comment by jatkinson** [comment]
Over 7 generations, since the late 70s, i think the GTI has held that sweet
spot. ;)

**Comment by nkkl** [comment]
Fair enough. If you'll stand by it for multiple editions of the car, I'm game.

**Comment by jatkinson** [comment]
:)

**Pull request merged**
